### ISSUE TITLE
收敛与搜索所需时间

### ISSUE THREAD

**Issue by wwHwo** [megvii-model/RLNAS#1]
您好，论文里关于搜索出来的架构的评价标准是收敛时间，请问实验结果中最终搜索出的架构实际收敛需要多长时间呢，搜索架构的时间大概是多长呢？

**Comment by larenzhang** [comment]
模型架构的评价标准是收敛速度，不是收敛时间哈．ImageNet数据集上，DARTS和MobileNet search space训练supernet(因为是single path sampling)和搜索出来的子模型训练时间相当的时间均是2~3天．
